 
// This is an autogenerated file. Editing this will have no effect 
 
const char *build_info_kubeka_name (void) { 
   return "kubeka"; 
} 
 
const char *build_info_kubeka_version (void) { 
   return "0.0.1"; 
} 
 
const char *build_info_kubeka_githash (void) { 
   return "0ec87153de4c32da34bfb64ef9baa0e5feaa2065"; 
} 
 
const char *build_info_kubeka_gitbranch (void) { 
   return "master"; 
} 
 
const char *build_info_kubeka_target (void) { 
   return "x86_64-linux-gnu"; 
} 
 
const char *build_info_kubeka_targetplatform (void) { 
   return "POSIX"; 
} 
 
const char *build_info_kubeka_hostname (void) { 
   return "Linux"; 
} 
 
const char *build_info_kubeka_ccversion (void) { 
   return "gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0"; 
} 
 
const char *build_info_kubeka_build (void) { 
   return "debug"; 
} 
 
const char *build_info_kubeka_timestamp (void) { 
   return "1707894299"; 
} 
 
const char *build_info_kubeka_homepage (void) { 
   return "http://www.rundata.co.za/products/kubeka"; 
} 
