 
// This is an autogenerated file. Editing this will have no effect 
 
#ifndef H_BUILD_INFO_kubeka 
#define H_BUILD_INFO_kubeka 
#ifdef __cplusplus 
extern "C" { 
#endif 
 
   const char *build_info_kubeka_name (void); 
   const char *build_info_kubeka_version (void); 
   const char *build_info_kubeka_githash (void); 
   const char *build_info_kubeka_gitbranch (void); 
   const char *build_info_kubeka_target (void); 
   const char *build_info_kubeka_targetplatform (void); 
   const char *build_info_kubeka_hostname (void); 
   const char *build_info_kubeka_ccversion (void); 
   const char *build_info_kubeka_build (void); 
   const char *build_info_kubeka_timestamp (void); 
   const char *build_info_kubeka_homepage (void); 
 
#ifdef __cplusplus 
}; 
#endif 
 
#endif